---
kind: pipeline
type: docker
name: build-ce-docker

trigger:
  branch:
    - develop
    - master
  event:
    - push
    - tag
    - manual

clone:
  depth: 1

steps:
  - name: strip-enterprise-code
    image: alpine:3.19
    commands:
      - rm -rf enterprise
      - rm -rf spec/enterprise

  - name: set-chatwoot-edition
    image: alpine:3.19
    commands:
      - echo -en '\nENV CW_EDITION="ce"' >> docker/Dockerfile

  - name: build-and-push
    image: thegeeklab/drone-docker-buildx:24
    privileged: true
    settings:
      repo: boro/chatwoot
      dockerfile: docker/Dockerfile
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - ${DRONE_BRANCH}-ce
      cache_from:
        - 'type=registry\\,ref=boro/chatwoot:buildcache-ce'
      cache_to: type=registry,ref=boro/chatwoot:buildcache-ce,mode=max
    when:
      branch:
        - develop

  - name: build-and-push-master
    image: thegeeklab/drone-docker-buildx:24
    privileged: true
    settings:
      repo: boro/chatwoot
      dockerfile: docker/Dockerfile
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - latest-ce
      cache_from:
        - 'type=registry\\,ref=boro/chatwoot:buildcache-ce'
    when:
      branch:
        - master

  - name: build-and-push-tag
    image: thegeeklab/drone-docker-buildx:24
    privileged: true
    settings:
      repo: boro/chatwoot
      dockerfile: docker/Dockerfile
      # platforms:
      #   - linux/amd64
      #   - linux/arm64
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - ${DRONE_TAG}-ce
      cache_from:
        - 'type=registry\\,ref=boro/chatwoot:buildcache-ce'
    when:
      event:
        - tag
